### ISSUE TITLE
Why does the pcre module use PCRE and not PCRE2?

### ISSUE THREAD

**Issue by srackham** [vlang/pcre#5]
I'm curious to know the reason why the newer PCRE2 library is not used (the  older PCRE library ["is now at end of life, and is no longer being actively maintained"](https://www.pcre.org/)).

**Comment by medvednikov** [comment]
I didn't know, we should switch.

**Comment by srackham** [comment]
I started on a patch but it quickly turned into a rewrite. See the [pcre2 module documentation](https://srackham.github.io/pcre2/pcre2.html) and the [Github repo](https://github.com/srackham/pcre2).

The functions and methods are similar to those in Go's regex package which should should ease porting Go code.

So far only tested on Linux.
